on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test
name: "Build & Release"
jobs:
  build:
    name: relese
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          flutter-version: '12.x'
      - run: flutter pub get
      - run: flutter build apk --debug
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
         
    
