on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test
name: "Build & Release"
jobs:
  build:
    name: relese
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Push to Release
        #uses: ncipollo/release-action@v1
        uses: ActionDemo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
      - name: Upload PGYER File
        uses: PGYER/pgyer-upload-app-action@v1.3
        with:
          _api_key: ${{ secrets.PGYER_API_TOKEN }}
          appFilePath: "build/app/outputs/apk/release/*"
         
    
